### ISSUE TITLE
输入出发和到达城市之后出现错误

### ISSUE THREAD

**Issue by YOURDD** [Black-Cyan/autoGrabTicketsScript#4]
已经成功打开了浏览器，输入到达城市之后报错如下，是我的环境问题吗：

请输入出发日期（YYYY-MM-DD）：2025-01-02
请输入出发城市：长春
请输入到达城市：贵阳
Traceback (most recent call last):
  File "C:\Users\URDD\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\URDD\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\URDD\AppData\Local\Programs\Python\Python313\Lib\json\decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\URDD\AppData\Local\Programs\Python\Python313\Lib\json\decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Download\autoGrabTicketsScript-master\script.py", line 41, in <module>
    json_data = response.json()
  File "C:\Users\URDD\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

进程已结束，退出代码为 1

**Comment by Black-Cyan** [comment]
未获取到相应的json数据导致的。铁路12306只能购买15日以内的车票，现在暂时没有1月2日的车票信息，所以无法获取到车票信息的json。你可以等到12月19日再使用该脚本购买1月2日的车票。

**Comment by YOURDD** [comment]
> 未获取到相应的json数据导致的。铁路12306只能购买15日以内的车票，目前暂时没有1月2日的车票信息，所以无法获取到相应的json数据信息。您可以等到12月19日再使用该剧本购买了1月2日的车票。

懂得了，但是有个问题，现在显示开票日期19号的12:00，是不是要等到19号12:00之前运行脚本等12:00他自动抢票

**Comment by BlackCyan07** [comment]
是的

**Comment by YOURDD** [comment]
> 未获取到相应的json数据导致的。铁路12306只能购买15日以内的车票，目前暂时没有1月2日的车票信息，所以无法获取到相应的json数据信息。您可以等到12月19日再使用该剧本购买了1月2日的车票。

懂了，但是我有个小问题，现在显示开票日期为19号的12:00，是不是要等到19号的时候，在12:00之前运行脚本等12:00他自动抢票

**Comment by Black-Cyan** [comment]
> > 未获取到相应的json数据导致的。铁路12306只能购买15日以内的车票，目前暂时没有1月2日的车票信息，所以无法获取到相应的json数据信息。您可以等到12月19日再使用该剧本购买了1月2日的车票。
> 
> 
> 
> 懂了，但是我有个小问题，现在显示开票日期为19号的12:00，是不是要等到19号的时候，在12:00之前运行脚本等12:00他自动抢票

是的

**Comment by YOURDD** [comment]
> > > 未获取到相应的json数据导致的。铁路12306只能购买15日以内的车票，目前暂时没有1月2日的车票信息，所以无法获取到相应的json数据信息。您可以等到12月19日再使用该剧本购买了1月2日的车票。
> > 
> > 
> > 懂了，但是我有一个小问题，现在显示开票日期为19号的12:00，是不是要等到19号的时候，在12:00之前运行脚本等12:00他自动抢票
> 
> 是的

感谢回复
